akshay_product/moviesproject/moviesapp/urls.py
from django.urls import path
from  . import views
app_name='moviesapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/', views.add_movie,name='add_movie'),
    path("update/<int:id>/",views.update,name="update"),
    path("delete/<int:id>/", views.delete, name="delete"),
]

akshay_product/moviesproject/moviesproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("moviesapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

akshay_product/moviesproject/moviesapp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__ (self):
        return self.name

akshay_product/moviesproject/moviesapp/forms.py
from django import forms
from.models import Movies

class MoviesForm(forms.ModelForm):
    class Meta:
        model=Movies
        fields=['name','desc','year','img']  #edit fields

akshay_product/moviesproject/moviesapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from  . models import Movies
from.forms import MoviesForm

# Create your views here.
def index(request):
    movie=Movies.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,"index.html",context)
def detail(request,movie_id):
    movie=Movies.objects.get(id=movie_id)
    return  render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movies(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")

def update(request,id):
    movies=Movies.objects.get(id=id)
    form=MoviesForm(request.POST or None,request.FILES,instance=movies)
    if form. is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'movies':movies})

def delete(request,id):
    if request.method=='POST':
        movies=Movies.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')

akshay_product/moviesproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     <input type="text" name="name" placeholder="enter ur movie name">
    <input type="text" name="desc" placeholder="enter ur movie description">
    <input type="text" name="year" placeholder="enter ur movie year">
    <input type="file" name="img" >
    <input type="submit" >
</form>
{% endblock %}

akshay_product/moviesproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    online movie store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

akshay_product/moviesproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are you want to delete this movie?
  <input type="submit">
</form>

akshay_product/moviesproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">

        </div>
<div class="col-md-6">
   <h4> {{movie.name}}</h4>
   <h6> {{movie.desc}}</h6>
   <h6> {{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'moviesapp:update' movie.id %}"> update </a>
    <a class="btn btn-danger" href="{% url 'moviesapp:delete' movie.id %}"> delete </a>

</div>
    </div>
</div>
{% endblock %}

akshay_product/moviesproject/templates/edit.html
<body style="background-color:skyblue;">


</body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

akshay_product/moviesproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="..." width="100px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'moviesapp:detail' i.id %}" class="btn btn-primary">click here</a>
  </div>
</div>
        </div>
        {% endfor %}

    </div>
</div>




{% endblock %}